name: CI

on:
  push:

permissions:
  contents: read

jobs:
  eval:
    runs-on: ubuntu-latest
    outputs:
      derivations: ${{ steps.eval.outputs.derivations }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
        with:
          installer-version: 2.35.1
      - uses: Mic92/hestia@f1f4df2801140a36398ed423533c8460618539df # v3.0.1
        with:
          version: v3.0.1
          upstream-cache-filter: true
      - id: eval
        name: Run nix-eval-jobs
        run: |
          echo "derivations=$(
            nix run --impure --expr 'import (import ./lon.nix).nixpkgs { }' nix-eval-jobs -- \
              --check-cache-status . | jq -cs 'map({attr, isCached})'
          )" >> "$GITHUB_OUTPUT"

  build:
    needs: eval
    runs-on: ubuntu-latest
    name: build (${{ matrix.derivation.attr }})
    strategy:
      fail-fast: false
      matrix:
        derivation: ${{ fromJson(needs.eval.outputs.derivations) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: ${{ !matrix.derivation.isCached }}
      - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
        if: ${{ !matrix.derivation.isCached }}
        with:
          installer-version: 2.35.1
      - uses: Mic92/hestia@f1f4df2801140a36398ed423533c8460618539df # v3.0.1
        if: ${{ !matrix.derivation.isCached }}
        with:
          version: v3.0.1
          upstream-cache-filter: true
      - run: nix build -f . '${{ matrix.derivation.attr }}' -L
        if: ${{ !matrix.derivation.isCached }}
